In [1]:
import numpy as np

In [2]:
# upper limit 5
np.random.randint(5, size = 7)

array([0, 2, 4, 1, 4, 4, 4])

In [3]:
np.random.randint(2,10, size = (3,2))

array([[3, 9],
       [2, 2],
       [4, 6]])

In [5]:
#random from 0-1
np.random.random(8)

array([0.75173914, 0.02366588, 0.46298845, 0.763311  , 0.01537529,
       0.69913724, 0.7229784 , 0.35988715])

In [8]:
#std norm
np.random.randn(10000).mean()

0.0022551504440832164

In [9]:
np.random.randn(10000).std()

1.0054774871292629

In [12]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [18]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [19]:
np.full((3,4),8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [20]:
np.full((3,4),8,dtype=float)

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [22]:
A=np.random.randint(6, size = (3,2))
A

array([[5, 1],
       [5, 5],
       [3, 4]])

In [23]:
A.ravel()

array([5, 1, 5, 5, 3, 4])

In [26]:
A.ravel(order='F') #fortan order

array([5, 5, 3, 1, 5, 4])

In [27]:
A.reshape(1,6)

array([[5, 1, 5, 5, 3, 4]])

In [29]:
A.reshape(2,3)

array([[5, 1, 5],
       [5, 3, 4]])

In [30]:
A.reshape(-1,3) # do not need to specify one of the dimension

array([[5, 1, 5],
       [5, 3, 4]])

In [33]:
A.T #Transpose will be different from reshape

array([[5, 5, 3],
       [1, 5, 4]])

In [34]:
B=np.random.randint(6, size = (4,3))
B

array([[2, 3, 4],
       [2, 0, 4],
       [5, 1, 4],
       [3, 3, 1]])

In [35]:
np.vsplit(B,2) #Split it into two np arrays

[array([[2, 3, 4],
        [2, 0, 4]]), array([[5, 1, 4],
        [3, 3, 1]])]

In [36]:
np.vsplit(B,2)[1]

array([[5, 1, 4],
       [3, 3, 1]])

In [38]:
np.hsplit(B,3)

[array([[2],
        [2],
        [5],
        [3]]), array([[3],
        [0],
        [1],
        [3]]), array([[4],
        [4],
        [4],
        [1]])]

In [39]:
c=np.hsplit(B,3)

In [40]:
np.concatenate(c)

array([[2],
       [2],
       [5],
       [3],
       [3],
       [0],
       [1],
       [3],
       [4],
       [4],
       [4],
       [1]])

In [42]:
a=np.array([1,23,4])
b=np.array([12,23,43])
np.concatenate((a,b))

array([ 1, 23,  4, 12, 23, 43])

In [43]:
np.concatenate((a.reshape(-1,1),b.reshape(-1,1)))

array([[ 1],
       [23],
       [ 4],
       [12],
       [23],
       [43]])

In [44]:
A1=np.random.randint(6, size = (3,2))
A2=np.random.randint(6, size = (3,2))
A3=np.random.randint(6, size = (3,2))

In [46]:
np.vstack((A1,A2,A3))

array([[4, 1],
       [0, 3],
       [0, 5],
       [1, 4],
       [5, 0],
       [5, 2],
       [4, 2],
       [4, 0],
       [5, 3]])

In [56]:
A=B[0:3,:]
A

array([[2, 3, 4],
       [2, 0, 4],
       [5, 1, 4]])

In [57]:
np.linalg.det(A)

36.0

In [58]:
np.linalg.inv(A)

array([[-1.11111111e-01, -2.22222222e-01,  3.33333333e-01],
       [ 3.33333333e-01, -3.33333333e-01,  2.84672570e-18],
       [ 5.55555556e-02,  3.61111111e-01, -1.66666667e-01]])

In [59]:
np.linalg.eig(A)

(array([ 8.91914368+0.j       , -1.45957184+1.3805477j,
        -1.45957184-1.3805477j]),
 array([[ 0.58465673+0.j        , -0.60454786+0.j        ,
         -0.60454786-0.j        ],
        [ 0.43750101+0.j        ,  0.04838462-0.58516486j,
          0.04838462+0.58516486j],
        [ 0.68320522+0.j        ,  0.48658072+0.23022186j,
          0.48658072-0.23022186j]]))

In [66]:
C1=np.random.randint(6, size = (3,3))
C2=np.random.randint(6, size = (3,3))

In [67]:
np.matmul(C1,C2)

array([[20, 15, 30],
       [12, 16, 14],
       [ 8,  6, 12]])

In [68]:
np.dot(C1,C2)

array([[20, 15, 30],
       [12, 16, 14],
       [ 8,  6, 12]])

In [69]:
C1*C2

array([[20,  0, 20],
       [ 4,  4,  4],
       [ 0,  0,  4]])